name: Auto Release

on:
  push:
    branches:
      - main
      - auto-release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Bun Setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: INstall Dependencies
        run: bun install
      - name: Generate Static Website
        run: |
          bun generate
          tar -czvf static_website.tar.gz .output/public
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./static_website.tar.gz
          asset_name: static_website.tar.gz
          asset_content_type: application/gzip
